# **Tensors**

**Disclaimer**: large parts of the lab are taken from [Deep Learning with PyTorch: A 60 Minute Blitz](https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html) by [Soumith Chintala](http://soumith.ch/) and lectures material of [Sebastian Goldt](https://datascience.sissa.it/research-unit/12/theory-of-neural-networks).

PyTorch _uses_ tensors, i.e. specialized data structure that are basically the same as a numpy array. The have nothing to do with the learning procedure: they are generic n-dimensional arrays with data in them (inputs, outputs, parameters of the net).

 _**Why do we use them?**_ 
They are able to run on
GPUs or specialized hardware that lead to more fast results.

_**I am not familiar with ndarrays (false, see last week Lab), do I have to worry?**_
No worries, let us go thorugh this quick introduction!


**First thing first**: import Pytorch and numpy

In [ ]:
import torch
import numpy as np

Tensors can be _directly_ defined from data

In [ ]:
data = [[1, 2],[3, 4]] # what's the type?
x_data = torch.tensor(data)

Tensors can be created _from NumPy arrays_ (and [vice versa](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#bridge-to-np-label)).

In [ ]:
np_array = np.array(data) # what's the type?
x_np = torch.from_numpy(np_array)


Tensors can be created from _other tensors_ with the same properties (say shape, datatype), unless overridden.

In [ ]:
x_ones = torch.zeros_like(x_data) # retains the properties of x_data
print(f"Zeros: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random: \n {x_rand} \n")

Zeros: 
 tensor([[0, 0],
        [0, 0]]) 

Random: 
 tensor([[0.4706, 0.1125],
        [0.3981, 0.2365]]) 



_What about the shape?_  The shape is a tuple with the dimensions. Let us see how to use it 

In [ ]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random: \n {rand_tensor} \n")
print(f"Ones: \n {ones_tensor} \n")
print(f"Zeros: \n {zeros_tensor}")

Random: 
 tensor([[0.4486, 0.7121, 0.6916],
        [0.4367, 0.2485, 0.6414]]) 

Ones: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


The attributes of a tensor are 
* shape, 
* datatype,
* the device of storage.

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


 **Operations**

There are _hundreds_ tensor operations: indexing, slicing,
mathematical operations, transposing... [Give a look](https://pytorch.org/docs/stable/torch.html)!

Each operation can be performed on GPU (faster then
CPU). On Colab, to allocate a GPU go to Edit > Notebook
Settings.





In [ ]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

Some examples now follow: if you are familiar with numpy, it is a piece of cake

_Indexing and slicing_

In [ ]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


_Joining tensors_


In [ ]:
t1 = torch.cat([tensor, tensor, tensor], dim=0)
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


_element-wise tensor multiplication_



In [ ]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor * tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


_matrix tensor multiplication_



In [ ]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


_tensor addition (in-place)_



In [ ]:
print(tensor, "\n")
tensor.add_(5) # change the same tensor
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


**Be carefull!**

 In-place operations are good for memory, but can be problematic when computing derivatives.



_From tensors to numpy (only on CPU)_



### Tensor to NumPy array



In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


if the tensor changes, the array changes (not vice versa).



In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


_From numpy to tensors_



In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

Changes in the NumPy array reflects in the tensor.



In [ ]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
